### ISSUE TITLE
Travis: Deployment of master branch not possible

### ISSUE THREAD

**Issue by sosterwalder** [MatthiasWinzeler/bfh-os2-toolchain#9]
I did some code changes on wednesday within the master-branch but it seems like travis is somehow not allowed to commit them and therefore the commit fails:

```
Preparing deploy
Expected(200) <=> Actual(401 Unauthorized)
body: "{\"id\":\"unauthorized\",\"error\":\"Invalid credentials provided.\"}" 
(wrong API key?)
failed to deploy
```

Maybe it has something to do with the layout-branch? I did merge the master- into the layout-branch, the build gets done successfully but no deployment happens.

**Comment by MatthiasWinzeler** [comment]
Thanks for reporting. Since I changed my heroku credentials, the api key needed to be updated as well.

It's fixed in https://github.com/MatthiasWinzeler/bfh-os2-toolchain/commit/54ac8d1aaa41a3636ca2cc82f87f929a98bf9bb5, builds seem to pass again:
https://travis-ci.org/MatthiasWinzeler/bfh-os2-toolchain/builds/24327602
